services:
  bot:
    build: .
    container_name: telegram_bot
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    command: python main.py
    networks:
      - sender

  redis:
    image: redis:7
    container_name: redis_storage
    networks:
      - sender

volumes:
  redis_data:
    driver: local

networks:
  sender:
    driver: bridge